routingRules:
  # Flights routing
  - domain: "mobility:flights:1.1.0"
    version: "1.1.0"
    targetType: "url"
    target:
      url: "http://bpp-flights:7001/"
    endpoints:
      - search
      - select
      - init
      - confirm
      - status
      - cancel
      - rating
      - support

  # Hotels routing  
  - domain: "hospitality:hotels:1.1.0"
    version: "1.1.0"
    targetType: "url"
    target:
      url: "http://bpp-hotels:7003/"
    endpoints:
      - search
      - select
      - init
      - confirm
      - status
      - cancel
      - rating
      - support